import type { Sport } from "@/lib/types";

export const riverSurfingStandingWave: Sport = {
  id: "river-surfing-standing-wave",
  slug: "river-surfing-standing-wave",
  name: "River Surfing (Standing Wave)",
  officialName: "International Surfing Association (ISA) — River Surfing Committee",
  aliases: ["Standing Wave Surfing", "River Waves", "Munich Eisbach Surfing"],
  shortDescription:
    "Non-tidal surfing on stationary river waves or river-generated wave features — most famous: Eisbach River wave in Munich (~1m standing wave, surfed continuously since 1972); competitive scene emerging 2010s+ with ISA River Surfing World Championship since 2019.",
  longDescription:
    "River Surfing is the discipline of surfing on stationary standing waves or hydraulic wave features generated by river currents (as opposed to ocean waves). Requires standing-wave river features — natural (rapids over shelves) or artificial (wave-shaper structures in urban rivers). Most iconic locations: (1) Eisbach River wave (Munich, Germany) — the Eisbach ('Ice Stream') artificial standing wave in central Munich has been continuously surfed since 1972 by generations of Bavarian river surfers; a permanent surf spot with dedicated queue etiquette; ~1m wave, water ~5-9°C year-round; (2) Bend Whitewater Park (Bend, Oregon, USA) — engineered river wave park; (3) Rhein wave (Basel, Switzerland); (4) Habitat 67 wave (Montreal — Ste. Anne rapids); (5) Prospect Park + Skookumchuck Narrows (Canada, tidal). Also river-wave features in Nepal (Sun Kosi), Slovenia (Soča), Czech Republic (Prague Trójský canál — Olympic slalom venue), Zambezi (Africa). International Surfing Association (ISA) recognized River Surfing as official discipline 2015; ISA River Surfing World Championship inaugurated 2019 in Argentina (Rio Petrohué). River surfing requires specialized shorter, more buoyant surfboards (~5ft8-6ft6 with concave hulls + fins optimized for standing waves) + wetsuits for cold river water + helmets. Munich Eisbach + Bend have strict local rules — waiting queue etiquette essential. Growing globally as urban surf-alternative + inland surf-culture. Distinct from tidal bore surfing (Amazon Pororoca, Severn Bore UK) which uses moving tidal-wave hydraulics.",
  category: "aquatic-sports",
  subCategory: "surfing on standing river waves",
  sportType: "individual", indoorOutdoor: "outdoor",
  isOlympic: false, isParalympic: false, isProfessional: false,
  season: "year-round", era: "20th-century", popularity: "niche",
  countryOfOrigin: "DE",
  regionOfOrigin: "Germany (Munich Eisbach — continuous surfing since 1972); global growth 2010s+",
  estimatedOrigin: "Munich Eisbach continuously surfed since 1972 (Bavarian surf pioneers); ISA formally recognized 2015; first World Championship 2019",
  players: { min: 1, max: 1 },
  equipment: [{ name: "River surfboard (5ft8-6ft6 with concave hull)", description: "Specialized shorter more buoyant board; brands include Kokopelli, Rockwater, Sunova Aircore." }, { name: "Wetsuit (5-6mm neoprene, cold rivers)", description: "Full wetsuit + hood + booties for cold river water (Eisbach 5-9°C year-round)." }, { name: "Helmet (mandatory at most river spots)", description: "Certified helmet — falls onto rocks are common; Munich Eisbach requires helmet." }, { name: "Impact vest / PFD (optional)", description: "Buoyancy for extended sessions." }, { name: "Leash (ankle or waist)", description: "River leashes must be quick-release for safety in current." }],
  duration: { approximateMinutes: 3, structure: "Per-ride: 30 seconds to 5+ minutes on wave; session: 1-3 hours (crowded queue-dependent)." },
  objective: "Perform maneuvers on standing wave; competitive: judged run scoring.",
  matchStructure: "Casual: queue-based; Competitive: heats + finals judged by ISA panel.",
  basicRules: [
    { title: "Queue etiquette strictly enforced (Munich, Bend)", body: "Wait your turn in line — jumping queue banned at established spots." },
    { title: "One surfer at a time on wave", body: "Standing waves accommodate one rider; wipeouts allow next in line." },
    { title: "Quick-release leash mandatory (river current)", body: "River leashes must release quickly if entrapment; regular ocean leash forbidden in current." },
    { title: "Helmet required at most spots", body: "Falls on rocks common; Munich Eisbach + Bend park mandate helmets." },
  ],
  scoring: { summary: "Casual: no scoring. ISA competition: 5-judge panel 0-10 on maneuvers + style + difficulty; best 2 of 4 waves aggregated.", winCondition: "Highest heat aggregate score." },
  positions: [{ name: "River surfer", role: "Sole competitor.", count: 1 }],
  officiating: { officials: ["ISA-certified judges (competitive)"], summary: "5-judge ISA panel at World Championship." },
  governingBodies: [{ name: "International Surfing Association (ISA)", founded: 1964, headquarters: "La Jolla, California, USA" }, { name: "River Surfing Committee (within ISA)", founded: 2015, headquarters: "ISA" }, { name: "Munich Surf Riders Association (Eisbach community body)", founded: 1975, headquarters: "Munich, Germany" }],
  majorCompetitions: [{ name: "ISA River Surfing World Championship", frequency: "biennial", founded: 2019, region: "rotating (Argentina 2019, Alberta Canada 2024)" }, { name: "Munich Eisbach Local Cup", frequency: "annual", founded: 1980, region: "Munich, Germany" }, { name: "Riversurfjam (Alberta Canada)", frequency: "annual", founded: 2013, region: "Kananaskis, Alberta" }],
  countriesPlayed: ["DEU (Munich Eisbach)", "USA (Bend Oregon)", "CHE (Basel)", "CAN (Montreal + Alberta)", "ARG (Rio Petrohué)", "NPL (Sun Kosi)", "SVN (Soča)", "CZE (Prague)"],
  famousAthletes: ["Munich Eisbach surf community (generational)", "Gerry Schlegel (GER — Eisbach pioneer)", "ISA River Surfing World Champions (recent: Argentina + Canada national teams)"],
  records: [
    { title: "Munich Eisbach continuously surfed since 1972", holder: "Munich Surf Riders", value: "Munich Eisbach standing wave continuously surfed by Bavarian surf community since 1972 — longest continuously-surfed inland wave in the world", year: 2024 },
    { title: "ISA River Surfing World Championship since 2019", holder: "International Surfing Association", value: "First ISA River Surfing World Championship held 2019 in Rio Petrohué, Argentina", year: 2019 },
    { title: "ISA recognized River Surfing as official discipline 2015", holder: "ISA", value: "ISA officially recognized River Surfing as international discipline 2015 — first inland surfing discipline formally sanctioned", year: 2015 },
  ],
  variants: ["natural-river-wave-standing", "artificial-urban-standing-wave-munich-eisbach", "bore-tidal-wave-surfing-amazon-severn", "engineered-park-wave-bend"],
  relatedSports: ["surfing-ocean", "stand-up-paddleboarding", "kayak-surfing", "wakesurfing-competitive"],
  skills: ["standing-wave balance (different from ocean wave)", "current-reading + edge control", "cold-water tolerance", "quick-release leash handling", "queue etiquette"],
  wikipediaTitle: "River surfing",
  sources: [{ label: "Wikipedia — River surfing", url: "https://en.wikipedia.org/wiki/River_surfing", publisher: "Wikipedia" }, { label: "ISA River Surfing", url: "https://isasurf.org/isa-river-surfing", publisher: "International Surfing Association" }],
  lastVerified: "2026-08-31",
  confidence: "verified",
};

export default riverSurfingStandingWave;
